#Actuator endpoint management
management:
  endpoints:
    web:
      exposure:
        include: '*'

#Eureka Client related settings
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka 
