#Application configs
spring:
  application:
    name: UserMS
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#Actuator endpoint management
management:
  endpoints:
    web:
      exposure:
        include: '*'

#Application Port
server:
  port: 9002
